#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
isis:
  reflector:
    explicit-annotations:
      action: true
    validator:
      allow-deprecated: false
      no-params-only: true
      explicit-object-type: true
      service-actions-only: true
      mixins-only: true

    facet:
      css-class-fa:
        patterns:
          new.*:fa-plus,\
          add.*:fa-plus-square,\
          create.*:fa-plus,\
          update.*:fa-edit,\
          delete.*:fa-trash,\
          save.*:fa-floppy-o,\
          change.*:fa-edit,\
          edit.*:fa-pencil-square-o,\
          maintain.*:fa-edit,\
          remove.*:fa-minus-square,\
          copy.*:fa-copy,\
          move.*:fa-exchange,\
          first.*:fa-star,\
          find.*:fa-search,\
          lookup.*:fa-search,\
          search.*:fa-search,\
          view.*:fa-search,\
          clear.*:fa-remove,\
          previous.*:fa-step-backward,\
          next.*:fa-step-forward,\
          list.*:fa-list, \
          all.*:fa-list, \
          download.*:fa-download, \
          upload.*:fa-upload, \
          export.*:fa-download,\
          switch.*:fa-exchange,\
          import.*:fa-upload,\
          execute.*:fa-bolt, \
          run.*:fa-bolt, \
          calculate.*:fa-calculator, \
          verify.*:fa-check-circle, \
          refresh.*:fa-refresh, \
          install.*:fa-wrench,\
          stop.*:fa-stop,\
          terminate.*:fa-stop,\
          cancel.*:fa-stop,\
          discard.*:fa-trash-o,\
          pause.*:fa-pause,\
          suspend.*:fa-pause,\
          resume.*:fa-play,\
          renew.*:fa-repeat,\
          reset.*:fa-repeat,\
          categorise.*:fa-folder-open-o,\
          assign.*:fa-hand-o-right,\
          approve.*:fa-thumbs-o-up,\
          decline.*:fa-thumbs-o-down

      css-class:
        patterns:
          delete.*:btn-danger,\
          discard.*:btn-warning,\
          remove.*:btn-warning


  objects:
    editing: false

  services:
    audit:
      objects: all
    command:
      actions: ignore_safe
      properties: all
    publish:
      objects: all
      actions: all
      properties: all

    injector:
      set-prefix: false

  value:
    format:
      date: dd-MM-yyyy

  viewer:
    wicket:
      application:
        menubars-layout-xml: domainapp/webapp/application/layout/menubars.layout.xml
        brand-logo-header: /images/apache-isis/logo-48x48.png
        favicon-url: /images/favicon.png
        name: Simple App
        css: css/application.css
        js: scripts/application.js
        about: Simple App
      welcome:
        file: welcome.html

      credit[0]:
        image: /images/apache-isis/logo-48x48.png
        name: Apache Isis
        url: http://isis.apache.org

      themes:
        initial: Flatly
        showChooser: true
        enabled: bootstrap-theme, Cerulean, Cosmo, Cyborg, Darkly, Flatly, Journal, Lumen, Paper, Readable, Sandstone, Simplex, Slate, Spacelab, Superhero, United, Yeti

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      development-utilities:
        enable: true


  persistor:
    datanucleus:
      impl:
        # note that properties under 'isis.persistor.datanucleus.impl' are passed through directly
        # to DataNucleus, and must use camelCase rather than kebab-case
        datanucleus:
          schema:
            validateTables: true
            validateConstraints: true

          persistenceByReachabilityAtCommit: false
          identifier:
            case: MixedCase

          cache:
            level2:
              type: none
              mode: ENABLE_SELECTIVE

spring:
  banner:
    location: banner.txt
