# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build w/ Maven + Jdk 15

on:
  push:
    branches:
      - jdo
      - jpa
      - jdo-SNAPSHOT
      - jpa-SNAPSHOT
  pull_request:
    branches:
      - jdo
      - jpa
      - jdo-SNAPSHOT
      - jpa-SNAPSHOT

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.3

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Print Maven Version
      run: mvn --version

    - name: Activate Cache for Maven Downloads
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-modules
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Prepare Build Versions
      shell: bash
      run: |
        ON_SNAPSHOT=$(echo $GITHUB_REF | grep SNAPSHOT)
        if [[ $ON_SNAPSHOT != "" ]]
        then
          PARENT=$(curl -X GET "https://nexus.incode.work/service/rest/v1/search?sort=version&repository=nightly-builds&group=org.apache.isis.app&name=isis-app-starter-parent" -H "accept: application/json" -s | jq '.items[0].version' | sed 's/"//g')
          echo "parentVersion = $PARENT"
          mvn versions:update-parent -DparentVersion="[$PARENT]"
        fi
        BASELINE=$(cat pom.xml | grep "<version>" | head -1 | awk -F'>' '{print $2}' | awk -F'<' '{print $1}')
        SHA_ID=$(echo $GITHUB_SHA | cut -c1-8)
        REVISION=${BASELINE}.$(date +%Y%m%d-%H%M)-${SHA_ID}
        mvn versions:set -DnewVersion=$REVISION

    - name: Print pom.xml
      shell: bash
      run: |
        cat pom.xml

    - name: Build with Maven
      shell: bash
      run: |
        mvn install

# uncomment and set environment variables to push to Docker registry
#    - name: Build and Push Docker Image
#      shell: bash
#      run: |
#        export REVISION=...
#        export DOCKER_REGISTRY_USERNAME
#        export DOCKER_REGISTRY_PASSWORD
#        mvn -pl webapp -Ddocker jib:build
